cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$VRoMybHM59H8TNI.h0/qh./QTbRPnl/w/w/SzshUL5iuHt9vZA4DC
    kanna:
      email: kanna@gmail.com
      logged_in: false
      name: kanna
      password: $2b$12$Nq63ps8fUzNSHGgQkTt/feXGPn6rYcxb4DkmSj6J.EIMDujjMeuRS
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$Nabi7ZRB//frkK6HHLu4ouSUABkx4hbsLT/RtttnnUx5bE3btepoK
    test:
      email: test@gmail.com
      first_name: test
      last_name: ing
      logged_in: false
      password: $2b$12$ZmK/e.Defkku00lcCMpoxe3WxJyDmJFDYvXDLusIelwTdmWnsjFW.
      password_hint: '1234'
      roles: null
preauthorized:
  emails:
  - melsby@gmail.com
